/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MuzikSlugRouteImport } from './routes/muzik.$slug'
import { Route as ListeSlugRouteImport } from './routes/liste.$slug'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as IncelemeSlugRouteImport } from './routes/inceleme.$slug'
import { Route as HaberSlugRouteImport } from './routes/haber.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MuzikSlugRoute = MuzikSlugRouteImport.update({
  id: '/muzik/$slug',
  path: '/muzik/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeSlugRoute = ListeSlugRouteImport.update({
  id: '/liste/$slug',
  path: '/liste/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IncelemeSlugRoute = IncelemeSlugRouteImport.update({
  id: '/inceleme/$slug',
  path: '/inceleme/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HaberSlugRoute = HaberSlugRouteImport.update({
  id: '/haber/$slug',
  path: '/haber/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/haber/$slug': typeof HaberSlugRoute
  '/inceleme/$slug': typeof IncelemeSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/liste/$slug': typeof ListeSlugRoute
  '/muzik/$slug': typeof MuzikSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/haber/$slug': typeof HaberSlugRoute
  '/inceleme/$slug': typeof IncelemeSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/liste/$slug': typeof ListeSlugRoute
  '/muzik/$slug': typeof MuzikSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/haber/$slug': typeof HaberSlugRoute
  '/inceleme/$slug': typeof IncelemeSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/liste/$slug': typeof ListeSlugRoute
  '/muzik/$slug': typeof MuzikSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/haber/$slug'
    | '/inceleme/$slug'
    | '/kategori/$slug'
    | '/liste/$slug'
    | '/muzik/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/haber/$slug'
    | '/inceleme/$slug'
    | '/kategori/$slug'
    | '/liste/$slug'
    | '/muzik/$slug'
  id:
    | '__root__'
    | '/'
    | '/haber/$slug'
    | '/inceleme/$slug'
    | '/kategori/$slug'
    | '/liste/$slug'
    | '/muzik/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HaberSlugRoute: typeof HaberSlugRoute
  IncelemeSlugRoute: typeof IncelemeSlugRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  ListeSlugRoute: typeof ListeSlugRoute
  MuzikSlugRoute: typeof MuzikSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muzik/$slug': {
      id: '/muzik/$slug'
      path: '/muzik/$slug'
      fullPath: '/muzik/$slug'
      preLoaderRoute: typeof MuzikSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liste/$slug': {
      id: '/liste/$slug'
      path: '/liste/$slug'
      fullPath: '/liste/$slug'
      preLoaderRoute: typeof ListeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inceleme/$slug': {
      id: '/inceleme/$slug'
      path: '/inceleme/$slug'
      fullPath: '/inceleme/$slug'
      preLoaderRoute: typeof IncelemeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haber/$slug': {
      id: '/haber/$slug'
      path: '/haber/$slug'
      fullPath: '/haber/$slug'
      preLoaderRoute: typeof HaberSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HaberSlugRoute: HaberSlugRoute,
  IncelemeSlugRoute: IncelemeSlugRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  ListeSlugRoute: ListeSlugRoute,
  MuzikSlugRoute: MuzikSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
